### ISSUE TITLE
unable to register in your deployed final site 

### ISSUE THREAD

**Issue by rahulguggilam** [PC-Ngumoha/katavault#2]
Unable to register in your deployed site even after filling all fields in the register page
 <img width="944" alt="n_pic" src="https://github.com/PC-Ngumoha/katavault/assets/94698414/bb806bb6-6636-4cf4-83bc-0f45787ef043">

**Comment by Rahulguggilam2003** [comment]
unable to register in your deployed site

**Comment by PC-Ngumoha** [comment]
Good day @Rahulguggilam2003, thank you for the observation. I suspect that the bug you encountered stems from the fact that I limited the phone number validation to only accept Nigerian phone numbers. I'll try to rectify this issue soon. Thanks once again.

**Comment by rahulguggilam** [comment]
@PC-Ngumoha   please include execution steps in the repository it will be helpful

**Comment by PC-Ngumoha** [comment]
Okay, I'll include that ASAP. Thanks for the advice.

**Comment by rahulguggilam** [comment]
@PC-Ngumoha  what is the node version you have used in the project

**Comment by PC-Ngumoha** [comment]
I used node v18 and npm v9 for the project.

**Comment by rahulguggilam** [comment]
katavault-main\node_modules\@ethersproject\bytes\lib\index.js:9
    return !!(value.toHexString);
                    ^

TypeError: Cannot read properties of undefined (reading 'toHexString')
    at isHexable (C:\Users\vasug\Desktop\project\katavault-main\node_modules\@ethersproject\bytes\lib\index.js:9:21)
    at hexlify (C:\Users\vasug\Desktop\project\katavault-main\node_modules\@ethersproject\bytes\lib\index.js:175:9)
    at new SigningKey (C:\Users\vasug\Desktop\project\katavault-main\node_modules\@ethersproject\signing-key\lib\index.js:20:82)
    at new Wallet (C:\Users\vasug\Desktop\project\katavault-main\node_modules\@ethersproject\wallet\lib\index.js:120:36)    at Object.<anonymous> (C:\Users\vasug\Desktop\project\katavault-main\src\config\contract.js:17:16)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)

Node.js v18.17.1
[nodemon] app crashed - waiting for file changes before starting...

**Comment by PC-Ngumoha** [comment]
What were you trying to do before you got this error?

**Comment by Rahulguggilam2003** [comment]
I have installed the required packages using **npm install** and after that to run the application I used the command 

 **npm run start**  in the main directory. 

After that I got this error. Please include execution steps in the repository. It will be helpful.

**Comment by rahulguggilam** [comment]
@PC-Ngumoha what is the issue here


 C:\Users\vasug\Desktop\project\katavault-main>npm run start

> katavault@1.0.0 start
> nodemon src/app.js

[nodemon] 3.0.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `node src/app.js`
C:\Users\vasug\Desktop\project\katavault-main\src\config\contract.js:16
const provider = new ethers.providers.JsonRpcProvider(API_URL);
TypeError: Cannot read properties of undefined (reading 'JsonRpcProvider')
    at Object.<anonymous> (C:\Users\vasug\Desktop\project\katavault-main\src\config\contract.js:16:39)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (C:\Users\vasug\Desktop\project\katavault-main\src\utils\contract.js:8:30)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
 is the value for api_url is this "https://api.pinata.cloud/pinning/pinFileToIPFS"
